name: GRPCTools Workflow

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ./build
          key: grpctools-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            grpctools-spm-
      - name: Build
        run: swift build
